interests = {
    "interests": {
        "pt_BR": [
            {"outdoor_activities": "atividades ao ar livre"},
            {"sports": "esportes"},
            {"fights": "lutas"},
            {"series": "séries"},
            {"snacks": "lanches"},
            {"good_products": "bons produtos"},
            {"curiosities": "curiosidades"},
            {"books": "livros"},
            {"dance": "dançar"},
            {"care": "cafuné"},
            {"barbecue": "churras em família"},
            {"flowers": "receber flores"},
            {"romance": "romance"},
            {"theater": "teatro"},
            {"corner": "canto"},
            {"cleaning": "limpeza"},
            {"games": "jogos mentais"},
            {"gardening": "jardinagem"},
            {"poetry": "poesia"},
            {"arts": "artes"},
            {"sunset": "pôr do sol"},
            {"occult": "ocultismo"},
            {"museums": "museus"},
            {"movies": "filmes"},
            {"travels": "viagens"},
            {"adventures": "aventuras"},
            {"philosophies": "filosofias"},
            {"economy": "economia"},
            {"policy": "política"},
            {"dinner": "jantar à luz de velas"},
            {"talks": "conversas longas"},
            {"pubs": "mesas de bar"},
            {"technologies": "tecnologia"},
            {"spirituality": "espiritualidade"},
            {"music": "música"},
            {"magic_tale": "contos sobre magia"},
        ]
    }
}
